/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.guru.stokguruv2.view;

import com.guru.stokguruv2.controller.KdvKartiController;
import com.guru.stokguruv2.entitie.dao.KdvKartiDao;
import com.guru.stokguruv2.gui.IKdvKarti;
import java.awt.event.ActionListener;
import java.util.Set;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class KdvKarti extends javax.swing.JInternalFrame implements IKdvKarti{

    /**
     * Creates new form KdvKarti
     */
    public KdvKarti() {
        initComponents();
        KdvKartiController kdvKartiController = new KdvKartiController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlKdvNavigation = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtKdvKodu = new javax.swing.JTextField();
        txtKdvAdi = new javax.swing.JTextField();
        txtKdvOrani = new javax.swing.JTextField();
        btnAra = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Kdv Kartı");

        pnlKdvNavigation.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("KDV Kodu");

        jLabel2.setText("KDV oranı");

        jLabel3.setText("KDV Adı");

        btnAra.setText("Ara");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlKdvNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnAra, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKdvKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtKdvAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtKdvOrani, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKdvKodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKdvAdi)
                    .addComponent(txtKdvOrani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAra))
                .addGap(72, 72, 72)
                .addComponent(pnlKdvNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlKdvNavigation;
    private javax.swing.JTextField txtKdvAdi;
    private javax.swing.JTextField txtKdvKodu;
    private javax.swing.JTextField txtKdvOrani;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getNavPanel() {
        return pnlKdvNavigation;
    }

    @Override
    public void buttonAra(ActionListener actionListener) {
       btnAra.addActionListener(actionListener);
    }

    @Override
    public String getKdvAdi() {
           return txtKdvAdi.getText();
    }

    @Override
    public void setKdvAdi(String kdvAdi) {
      txtKdvAdi.setText(kdvAdi);
        
    }

    @Override
    public String getKdvKodu() {
        return txtKdvKodu.getText();
    }

    @Override
    public void setKdvKodu(String kdvKodu) {
         txtKdvKodu.setText(kdvKodu);
    }

    @Override
    public String getKdvOrani() {
        return txtKdvOrani.getText();
    }

    @Override
    public void setKdvOrani(String kdvOrani) {
         txtKdvOrani.setText(kdvOrani);
    }
}
